import React from "react";
import Image from "next/image";
import Link from "next/link";
import { Section } from "@/components/ui/Section";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { siteContent } from "@/content/site";
import { Mail } from "lucide-react";
import { ProjectCard } from "@/components/ProjectCard";

// Ensure internal routes produced by content include a trailing slash to match
// the structure generated by `next export` (which uses directories).
function ensureTrailingSlash(href: string) {
  try {
    const url = new URL(href, "http://example.com");
    if (url.origin === "http://example.com") {
      // relative/internal URL
      return href.replace(/\/?$/, "/");
    }
  } catch {
    // if URL parsing fails, just add slash
    return href.replace(/\/?$/, "/");
  }
  return href;
}

export default async function Home() {
  const firstProject = siteContent.projects[0];
  const heroPrimaryHref = firstProject
    ? ensureTrailingSlash(`/projects/${firstProject.slug}`)
    : ensureTrailingSlash(siteContent.hero.ctas.primary.href);

  return (
    <div className="min-h-screen bg-white">
      {/* Skip to content link for accessibility */}
      <a
        href="#main-content"
        className="absolute top-0 left-0 -translate-y-full focus:translate-y-0 bg-[#59D5E0] text-black font-bold p-4 z-[100]"
      >
        Skip to main content
      </a>

      <div id="main-content">
        {/* Hero Section */}
        <Section className="bg-gradient-to-br from-[#59D5E0]/20 to-[#F5DD61]/20 py-36 md:py-56">
          <div className="max-w-5xl mx-auto text-center">
            <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-4">
              {siteContent.hero.title}
            </h1>
            <p className="text-lg md:text-xl text-gray-600 max-w-3xl mx-auto mb-8">
              {siteContent.hero.subtitle}
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <Button asChild size="lg" variant="secondary">
                <a href={heroPrimaryHref}>
                  {siteContent.hero.ctas.primary.text}
                </a>
              </Button>
              <Button asChild size="lg" variant="accent">
                <Link
                  href={siteContent.hero.ctas.secondary.href}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {siteContent.hero.ctas.secondary.text}
                </Link>
              </Button>
            </div>
          </div>
        </Section>

        {/* Case Studies */}
        <Section id="projects" className="bg-gray-50 py-20 sm:py-32">
          <div className="max-w-5xl mx-auto">
            <div className="text-center mb-12">
              <SectionHeading>Case Studies</SectionHeading>
              <p className="text-gray-600 max-w-2xl mx-auto">
                A look at projects that demonstrate my skills in cloud
                infrastructure, networking, and full-stack development.
              </p>
            </div>

            <div className="grid md:grid-cols-2 gap-8">
              {siteContent.projects.map((project) => (
                <ProjectCard key={project.slug} project={project} />
              ))}
            </div>
          </div>
        </Section>

        {/* About Me */}
        <Section id="about" className="py-20 sm:py-32">
          <div className="max-w-3xl mx-auto text-center">
            <SectionHeading>About Me</SectionHeading>
            {siteContent.about.profileImage && (
              <div className="mt-8 mb-6">
                <Image
                  src={siteContent.about.profileImage}
                  alt={siteContent.about.profileImageAlt || "Profile Icon"}
                  width={150}
                  height={150}
                  className="rounded-full mx-auto object-cover border-4 border-white shadow-lg"
                />
              </div>
            )}
            <p className="text-lg text-gray-600 mt-6 max-w-2xl mx-auto">
              {siteContent.about.content}
            </p>
          </div>
        </Section>

        {/* Skills */}
        <Section id="skills" className="bg-gray-50 py-20 sm:py-32">
          <div className="max-w-4xl mx-auto">
            <div className="text-center mb-12">
              <SectionHeading>Skills</SectionHeading>
            </div>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
              {siteContent.skills.map((skillGroup) => (
                <div key={skillGroup.group}>
                  <h3 className="font-bold text-lg text-gray-800 mb-3">
                    {skillGroup.group}
                  </h3>
                  <ul className="space-y-2">
                    {skillGroup.items.map((skill) => (
                      <li key={skill} className="text-gray-600">
                        {skill}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        </Section>

        {/* Contact */}
        <Section id="contact" className="py-20 sm:py-32">
          <div className="max-w-xl mx-auto text-center">
            <SectionHeading>Get in Touch</SectionHeading>
            <p className="text-gray-600 mb-8">
              I'm always open to discussing new projects, creative ideas, or
              opportunities to be part of your vision.
            </p>
            <Button asChild size="lg" variant="secondary">
              <a href={`mailto:${siteContent.links.email}`}>
                <Mail className="w-5 h-5 mr-2" />
                Say Hello
              </a>
            </Button>
          </div>
        </Section>
      </div>
    </div>
  );
}
